services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        APP_NAME: api
      no_cache: true
    ports:
      - "4200:4200"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        APP_NAME: web
      no_cache: true
    ports:
      - "3000:3000"
    depends_on:
      - api
