/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardApplicationIdIndexRouteImport } from './routes/dashboard/$applicationId/index'
import { Route as DashboardApplicationIdResolveRouteImport } from './routes/dashboard/$applicationId/resolve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApplicationIdIndexRoute =
  DashboardApplicationIdIndexRouteImport.update({
    id: '/dashboard/$applicationId/',
    path: '/dashboard/$applicationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardApplicationIdResolveRoute =
  DashboardApplicationIdResolveRouteImport.update({
    id: '/dashboard/$applicationId/resolve',
    path: '/dashboard/$applicationId/resolve',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$applicationId/resolve': typeof DashboardApplicationIdResolveRoute
  '/dashboard/$applicationId/': typeof DashboardApplicationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$applicationId/resolve': typeof DashboardApplicationIdResolveRoute
  '/dashboard/$applicationId': typeof DashboardApplicationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$applicationId/resolve': typeof DashboardApplicationIdResolveRoute
  '/dashboard/$applicationId/': typeof DashboardApplicationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/dashboard/$applicationId/resolve'
    | '/dashboard/$applicationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/$applicationId/resolve'
    | '/dashboard/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/dashboard/$applicationId/resolve'
    | '/dashboard/$applicationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardApplicationIdResolveRoute: typeof DashboardApplicationIdResolveRoute
  DashboardApplicationIdIndexRoute: typeof DashboardApplicationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$applicationId/': {
      id: '/dashboard/$applicationId/'
      path: '/dashboard/$applicationId'
      fullPath: '/dashboard/$applicationId/'
      preLoaderRoute: typeof DashboardApplicationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$applicationId/resolve': {
      id: '/dashboard/$applicationId/resolve'
      path: '/dashboard/$applicationId/resolve'
      fullPath: '/dashboard/$applicationId/resolve'
      preLoaderRoute: typeof DashboardApplicationIdResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApplicationIdResolveRoute: DashboardApplicationIdResolveRoute,
  DashboardApplicationIdIndexRoute: DashboardApplicationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
