// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import type { Client, Options as Options2, TDataShape } from "./client";
import type {
  GetApiV1AuthMeData,
  GetApiV1AuthMeErrors,
  GetApiV1AuthMeResponses,
  GetApiV1DataByApplicationIdData,
  GetApiV1DataByApplicationIdErrors,
  GetApiV1DataByApplicationIdHistoryData,
  GetApiV1DataByApplicationIdHistoryResponses,
  GetApiV1DataByApplicationIdResponses,
  GetApiV1DataListData,
  GetApiV1DataListResponses,
  GetApiV1DataSyncData,
  GetApiV1DataSyncErrors,
  GetApiV1DataSyncResponses,
  GetApiV1MiscDebugData,
  GetApiV1MiscDebugResponses,
  PostApiV1AuthLoginData,
  PostApiV1AuthLoginErrors,
  PostApiV1AuthLoginResponses,
  PostApiV1DataByApplicationIdResolveData,
  PostApiV1DataByApplicationIdResolveResponses,
} from "./types.gen";

import { client } from "./client.gen";
import {
  zGetApiV1DataByApplicationIdHistoryPath,
  zGetApiV1DataByApplicationIdPath,
  zGetApiV1DataListQuery,
  zGetApiV1DataSyncQuery,
  zPostApiV1AuthLoginBody,
  zPostApiV1DataByApplicationIdResolveBody,
  zPostApiV1DataByApplicationIdResolvePath,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class AuthService {
  /**
   * Login with email and password
   *
   * Authenticate user and set httpOnly session cookie
   */
  public static postApiV1AuthLogin<ThrowOnError extends boolean = false>(
    options: Options<PostApiV1AuthLoginData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      PostApiV1AuthLoginResponses,
      PostApiV1AuthLoginErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: zPostApiV1AuthLoginBody,
            path: z.never().optional(),
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/auth/login",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get current user session
   *
   * Returns the current user's session information
   */
  public static getApiV1AuthMe<ThrowOnError extends boolean = false>(
    options?: Options<GetApiV1AuthMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetApiV1AuthMeResponses,
      GetApiV1AuthMeErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/auth/me",
      ...options,
    });
  }
}

export class MiscService {
  /**
   * Get Debug
   *
   * Get debug info
   */
  public static getApiV1MiscDebug<ThrowOnError extends boolean = false>(
    options?: Options<GetApiV1MiscDebugData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetApiV1MiscDebugResponses, unknown, ThrowOnError>({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/misc/debug",
      ...options,
    });
  }
}

export class IntegrationsService {
  /**
   * Get Integrations List
   *
   * Get list of all integrations with their sync status
   */
  public static getApiV1DataList<ThrowOnError extends boolean = false>(
    options?: Options<GetApiV1DataListData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetApiV1DataListResponses, unknown, ThrowOnError>({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: zGetApiV1DataListQuery.optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/data/list",
      ...options,
    });
  }

  /**
   * [EXTERNAL] Get Data Sync
   *
   * Proxy to external API to get sync approval data for an application
   */
  public static getApiV1DataSync<ThrowOnError extends boolean = false>(
    options: Options<GetApiV1DataSyncData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetApiV1DataSyncResponses,
      GetApiV1DataSyncErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: zGetApiV1DataSyncQuery,
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/data/sync",
      ...options,
    });
  }

  /**
   * Get Integration Details
   *
   * Get detailed information about a specific integration
   */
  public static getApiV1DataByApplicationId<ThrowOnError extends boolean = false>(
    options: Options<GetApiV1DataByApplicationIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetApiV1DataByApplicationIdResponses,
      GetApiV1DataByApplicationIdErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: zGetApiV1DataByApplicationIdPath,
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/data/{application_id}",
      ...options,
    });
  }

  /**
   * Get Sync History
   *
   * Get historical sync events for an integration
   */
  public static getApiV1DataByApplicationIdHistory<ThrowOnError extends boolean = false>(
    options: Options<GetApiV1DataByApplicationIdHistoryData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetApiV1DataByApplicationIdHistoryResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: zGetApiV1DataByApplicationIdHistoryPath,
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/data/{application_id}/history",
      ...options,
    });
  }

  /**
   * Resolve Sync Changes
   *
   * Accept or discard sync changes
   */
  public static postApiV1DataByApplicationIdResolve<ThrowOnError extends boolean = false>(
    options: Options<PostApiV1DataByApplicationIdResolveData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      PostApiV1DataByApplicationIdResolveResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: zPostApiV1DataByApplicationIdResolveBody.optional(),
            path: zPostApiV1DataByApplicationIdResolvePath,
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/data/{application_id}/resolve",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
