// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import type { Client, Options as Options2, TDataShape } from "./client";
import type {
  GetApiV1ApplicationsListData,
  GetApiV1ApplicationsListResponses,
  GetApiV1AuthMeData,
  GetApiV1AuthMeErrors,
  GetApiV1AuthMeResponses,
  GetApiV1MiscStatusData,
  GetApiV1MiscStatusResponses,
  GetApiV1MiscStatusWithParamsData,
  GetApiV1MiscStatusWithParamsErrors,
  GetApiV1MiscStatusWithParamsResponses,
  PostApiV1AuthLoginData,
  PostApiV1AuthLoginErrors,
  PostApiV1AuthLoginResponses,
} from "./types.gen";

import { client } from "./client.gen";
import {
  zGetApiV1ApplicationsListQuery,
  zGetApiV1MiscStatusWithParamsQuery,
  zPostApiV1AuthLoginBody,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class AuthService {
  /**
   * Login with email and password
   *
   * Authenticate user and set httpOnly session cookie
   */
  public static postApiV1AuthLogin<ThrowOnError extends boolean = false>(
    options: Options<PostApiV1AuthLoginData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      PostApiV1AuthLoginResponses,
      PostApiV1AuthLoginErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: zPostApiV1AuthLoginBody,
            path: z.never().optional(),
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/auth/login",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get current user session
   *
   * Returns the current user's session information
   */
  public static getApiV1AuthMe<ThrowOnError extends boolean = false>(
    options?: Options<GetApiV1AuthMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetApiV1AuthMeResponses,
      GetApiV1AuthMeErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/auth/me",
      ...options,
    });
  }
}

export class MiscService {
  /**
   * Get Status
   *
   * Get ok status
   */
  public static getApiV1MiscStatus<ThrowOnError extends boolean = false>(
    options?: Options<GetApiV1MiscStatusData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetApiV1MiscStatusResponses, unknown, ThrowOnError>({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: z.never().optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/misc/status",
      ...options,
    });
  }

  /**
   * Get Status with Params
   *
   * Get ok status
   */
  public static getApiV1MiscStatusWithParams<ThrowOnError extends boolean = false>(
    options: Options<GetApiV1MiscStatusWithParamsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetApiV1MiscStatusWithParamsResponses,
      GetApiV1MiscStatusWithParamsErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: zGetApiV1MiscStatusWithParamsQuery,
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/misc/status-with-params",
      ...options,
    });
  }
}

export class ApplicationsService {
  /**
   * Get Applications List
   *
   * Get list of all applications with their sync status
   */
  public static getApiV1ApplicationsList<ThrowOnError extends boolean = false>(
    options?: Options<GetApiV1ApplicationsListData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetApiV1ApplicationsListResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await z
          .object({
            body: z.never().optional(),
            path: z.never().optional(),
            query: zGetApiV1ApplicationsListQuery.optional(),
          })
          .parseAsync(data),
      responseType: "json",
      url: "/api/v1/applications/list",
      ...options,
    });
  }
}
