// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import type {
  GetApiV1MiscStatusData,
  GetApiV1MiscStatusResponses,
  GetApiV1MiscStatusWithParamsData,
  GetApiV1MiscStatusWithParamsErrors,
  GetApiV1MiscStatusWithParamsResponses,
} from "./types.gen";

import { client } from "./client.gen";
import { zGetApiV1MiscStatusData, zGetApiV1MiscStatusWithParamsData } from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class MiscService {
  /**
   * Get Status
   *
   * Get ok status
   */
  public static getApiV1MiscStatus<ThrowOnError extends boolean = false>(
    options?: Options<GetApiV1MiscStatusData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetApiV1MiscStatusResponses, unknown, ThrowOnError>({
      requestValidator: async (data) => await zGetApiV1MiscStatusData.parseAsync(data),
      responseType: "json",
      url: "/api/v1/misc/status",
      ...options,
    });
  }

  /**
   * Get Status with Params
   *
   * Get ok status
   */
  public static getApiV1MiscStatusWithParams<ThrowOnError extends boolean = false>(
    options: Options<GetApiV1MiscStatusWithParamsData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetApiV1MiscStatusWithParamsResponses,
      GetApiV1MiscStatusWithParamsErrors,
      ThrowOnError
    >({
      requestValidator: async (data) => await zGetApiV1MiscStatusWithParamsData.parseAsync(data),
      responseType: "json",
      url: "/api/v1/misc/status-with-params",
      ...options,
    });
  }
}
