// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:4200" | (string & {});
};

/**
 * A successful response object
 */
export type OkResponse = {
  /**
   * Whether the response indicates success
   */
  ok: boolean;
  /**
   * The response data
   */
  data: unknown;
  /**
   * Human-readable status message of the response
   */
  message: string;
  /**
   * Unique ID of the request
   */
  requestId: string;
};

export type Session = {
  id: string;
  user: {
    id: string;
    name: string;
    email: string;
    phone: string;
    role: string;
    status: string;
    createdAt: string;
    updatedAt: string;
  };
  createdAt: string;
  expiresAt: string;
};

export type User = {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: string;
  status: string;
  createdAt: string;
  updatedAt: string;
};

export type ChangeType = "ADD" | "UPDATE" | "DELETE";

export type Integration = {
  id: string;
  name: string;
  emoji: string;
  status: "synced" | "syncing" | "conflict" | "error";
  lastSyncedAt: string;
  version: string;
};

export type SyncApproval = {
  application_name: string;
  changes: Array<{
    id: string;
    field_name: string;
    change_type: "ADD" | "UPDATE" | "DELETE";
    current_value?: string;
    new_value?: string;
  }>;
};

export type SyncChange = {
  id: string;
  field_name: string;
  change_type: "ADD" | "UPDATE" | "DELETE";
  current_value?: string;
  new_value?: string;
};

export type SyncData = {
  sync_approval: {
    application_name: string;
    changes: Array<{
      id: string;
      field_name: string;
      change_type: "ADD" | "UPDATE" | "DELETE";
      current_value?: string;
      new_value?: string;
    }>;
  };
  metadata: {
    [key: string]: unknown;
  };
};

export type SyncStatus = "synced" | "syncing" | "conflict" | "error";

/**
 * An error response object
 */
export type ErrorResponse = {
  /**
   * Whether the response indicates success
   */
  ok: boolean;
  /**
   * Specific error code
   */
  errorCode:
    | "MALFORMED_INPUT"
    | "NOT_FOUND"
    | "UNAUTHORIZED"
    | "FORBIDDEN"
    | "INTERNAL_SERVER_ERROR"
    | "UNSPECIFIED_ERROR";
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * Unique ID of the request
   */
  requestId: string;
};

export type PostApiV1AuthLoginData = {
  body: {
    email: string;
    password: string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type PostApiV1AuthLoginErrors = {
  /**
   * An error response object
   */
  400: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "MALFORMED_INPUT";
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
  /**
   * An error response object
   */
  401: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "UNAUTHORIZED";
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
  /**
   * An error response object
   */
  500: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "INTERNAL_SERVER_ERROR";
    /**
     * Human-readable error message
     */
    message: "Something went wrong. Please try again later.";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
  /**
   * A successful response object
   */
  200: {
    /**
     * Whether the response indicates success
     */
    ok: true;
    /**
     * The response data
     */
    data: {
      session: {
        id: string;
        user: {
          id: string;
          name: string;
          email: string;
          phone: string;
          role: string;
          status: string;
          createdAt: string;
          updatedAt: string;
        };
        createdAt: string;
        expiresAt: string;
      };
      token: string;
    };
    /**
     * Human-readable status message of the response
     */
    message: "Success";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type PostApiV1AuthLoginResponse =
  PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type GetApiV1AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type GetApiV1AuthMeErrors = {
  /**
   * An error response object
   */
  401: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "UNAUTHORIZED";
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
  /**
   * An error response object
   */
  500: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "INTERNAL_SERVER_ERROR";
    /**
     * Human-readable error message
     */
    message: "Something went wrong. Please try again later.";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1AuthMeError = GetApiV1AuthMeErrors[keyof GetApiV1AuthMeErrors];

export type GetApiV1AuthMeResponses = {
  /**
   * A successful response object
   */
  200: {
    /**
     * Whether the response indicates success
     */
    ok: true;
    /**
     * The response data
     */
    data: {
      id: string;
      name: string;
      email: string;
      phone: string;
      role: string;
      status: string;
      createdAt: string;
      updatedAt: string;
    };
    /**
     * Human-readable status message of the response
     */
    message: "Success";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1AuthMeResponse = GetApiV1AuthMeResponses[keyof GetApiV1AuthMeResponses];

export type GetApiV1MiscStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/misc/status";
};

export type GetApiV1MiscStatusResponses = {
  /**
   * A successful response object
   */
  200: {
    /**
     * Whether the response indicates success
     */
    ok: true;
    /**
     * The response data
     */
    data: "ok";
    /**
     * Human-readable status message of the response
     */
    message: "Success";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1MiscStatusResponse =
  GetApiV1MiscStatusResponses[keyof GetApiV1MiscStatusResponses];

export type GetApiV1MiscStatusWithParamsData = {
  body?: never;
  path?: never;
  query: {
    required: string;
    optional?: string;
  };
  url: "/api/v1/misc/status-with-params";
};

export type GetApiV1MiscStatusWithParamsErrors = {
  /**
   * An error response object
   */
  400: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "MALFORMED_INPUT";
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
  /**
   * An error response object
   */
  500: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "INTERNAL_SERVER_ERROR";
    /**
     * Human-readable error message
     */
    message: "Something went wrong. Please try again later.";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1MiscStatusWithParamsError =
  GetApiV1MiscStatusWithParamsErrors[keyof GetApiV1MiscStatusWithParamsErrors];

export type GetApiV1MiscStatusWithParamsResponses = {
  /**
   * A successful response object
   */
  200: {
    /**
     * Whether the response indicates success
     */
    ok: true;
    /**
     * The response data
     */
    data: "ok";
    /**
     * Human-readable status message of the response
     */
    message: "Success";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1MiscStatusWithParamsResponse =
  GetApiV1MiscStatusWithParamsResponses[keyof GetApiV1MiscStatusWithParamsResponses];

export type GetApiV1DataListData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
  };
  url: "/api/v1/data/list";
};

export type GetApiV1DataListResponses = {
  /**
   * A successful response object
   */
  200: {
    /**
     * Whether the response indicates success
     */
    ok: true;
    /**
     * The response data
     */
    data: Array<{
      id: string;
      name: string;
      emoji: string;
      status: "synced" | "syncing" | "conflict" | "error";
      lastSyncedAt: string;
      version: string;
    }>;
    /**
     * Human-readable status message of the response
     */
    message: "Success";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1DataListResponse = GetApiV1DataListResponses[keyof GetApiV1DataListResponses];

export type GetApiV1DataSyncData = {
  body?: never;
  path?: never;
  query: {
    application_id: "salesforce" | "hubspot" | "stripe" | "slack" | "zendesk" | "intercom";
  };
  url: "/api/v1/data/sync";
};

export type GetApiV1DataSyncErrors = {
  /**
   * External API error response
   */
  500: {
    code: string;
    message: string;
    error: string;
  };
};

export type GetApiV1DataSyncError = GetApiV1DataSyncErrors[keyof GetApiV1DataSyncErrors];

export type GetApiV1DataSyncResponses = {
  /**
   * Returns sync approval data from external API
   */
  200: {
    code: string;
    message: string;
    data: {
      sync_approval: {
        application_name: string;
        changes: Array<{
          id: string;
          field_name: string;
          change_type: "ADD" | "UPDATE" | "DELETE";
          current_value?: string;
          new_value?: string;
        }>;
      };
      metadata: {
        [key: string]: unknown;
      };
    };
  };
};

export type GetApiV1DataSyncResponse = GetApiV1DataSyncResponses[keyof GetApiV1DataSyncResponses];
