// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:4200" | (string & {});
};

/**
 * A successful response object
 */
export type OkResponse = {
  /**
   * Whether the response indicates success
   */
  ok: boolean;
  /**
   * The response data
   */
  data: unknown;
  /**
   * Human-readable status message of the response
   */
  message: string;
  /**
   * Unique ID of the request
   */
  requestId: string;
};

/**
 * An error response object
 */
export type ErrorResponse = {
  /**
   * Whether the response indicates success
   */
  ok: boolean;
  /**
   * Specific error code
   */
  errorCode:
    | "MALFORMED_INPUT"
    | "NOT_FOUND"
    | "UNAUTHORIZED"
    | "FORBIDDEN"
    | "INTERNAL_SERVER_ERROR"
    | "UNSPECIFIED_ERROR";
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * Unique ID of the request
   */
  requestId: string;
};

export type GetApiV1MiscStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/misc/status";
};

export type GetApiV1MiscStatusResponses = {
  /**
   * A successful response object
   */
  200: {
    /**
     * Whether the response indicates success
     */
    ok: true;
    /**
     * The response data
     */
    data: "ok";
    /**
     * Human-readable status message of the response
     */
    message: "Success";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1MiscStatusResponse =
  GetApiV1MiscStatusResponses[keyof GetApiV1MiscStatusResponses];

export type GetApiV1MiscStatusWithParamsData = {
  body?: never;
  path?: never;
  query: {
    required: string;
    optional?: string;
  };
  url: "/api/v1/misc/status-with-params";
};

export type GetApiV1MiscStatusWithParamsErrors = {
  /**
   * An error response object
   */
  400: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "MALFORMED_INPUT";
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
  /**
   * An error response object
   */
  500: {
    /**
     * Whether the response indicates success
     */
    ok: false;
    /**
     * Specific error code
     */
    errorCode: "INTERNAL_SERVER_ERROR";
    /**
     * Human-readable error message
     */
    message: "Something went wrong. Please try again later.";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1MiscStatusWithParamsError =
  GetApiV1MiscStatusWithParamsErrors[keyof GetApiV1MiscStatusWithParamsErrors];

export type GetApiV1MiscStatusWithParamsResponses = {
  /**
   * A successful response object
   */
  200: {
    /**
     * Whether the response indicates success
     */
    ok: true;
    /**
     * The response data
     */
    data: "ok";
    /**
     * Human-readable status message of the response
     */
    message: "Success";
    /**
     * Unique ID of the request
     */
    requestId: string;
  };
};

export type GetApiV1MiscStatusWithParamsResponse =
  GetApiV1MiscStatusWithParamsResponses[keyof GetApiV1MiscStatusWithParamsResponses];
