// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * A successful response object
 */
export const zOkResponse = z.object({
  ok: z.boolean(),
  data: z.unknown(),
  message: z.string(),
  requestId: z.string(),
});

export const zSession = z.object({
  id: z.string(),
  user: z.object({
    id: z.string(),
    name: z.string(),
    email: z
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
    phone: z.string(),
    role: z.string(),
    status: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
  createdAt: z.string(),
  expiresAt: z.string(),
});

export const zUser = z.object({
  id: z.string(),
  name: z.string(),
  email: z
    .email()
    .regex(
      /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
    ),
  phone: z.string(),
  role: z.string(),
  status: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

/**
 * An error response object
 */
export const zErrorResponse = z.object({
  ok: z.boolean(),
  errorCode: z.enum([
    "MALFORMED_INPUT",
    "NOT_FOUND",
    "UNAUTHORIZED",
    "FORBIDDEN",
    "INTERNAL_SERVER_ERROR",
    "UNSPECIFIED_ERROR",
  ]),
  message: z.string(),
  requestId: z.string(),
});

export const zPostApiV1AuthLoginBody = z.object({
  email: z.email(),
  password: z.string(),
});

/**
 * A successful response object
 */
export const zPostApiV1AuthLoginResponse = z.object({
  ok: z.literal(true),
  data: z.object({
    session: z.object({
      id: z.string(),
      user: z.object({
        id: z.string(),
        name: z.string(),
        email: z.email(),
        phone: z.string(),
        role: z.string(),
        status: z.string(),
        createdAt: z.string(),
        updatedAt: z.string(),
      }),
      createdAt: z.string(),
      expiresAt: z.string(),
    }),
    token: z.string(),
  }),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

/**
 * A successful response object
 */
export const zGetApiV1AuthMeResponse = z.object({
  ok: z.literal(true),
  data: z.object({
    id: z.string(),
    name: z.string(),
    email: z.email(),
    phone: z.string(),
    role: z.string(),
    status: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

/**
 * A successful response object
 */
export const zGetApiV1MiscStatusResponse = z.object({
  ok: z.literal(true),
  data: z.enum(["ok"]),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

export const zGetApiV1MiscStatusWithParamsQuery = z.object({
  required: z.string().min(1),
  optional: z.string().min(1).optional(),
});

/**
 * A successful response object
 */
export const zGetApiV1MiscStatusWithParamsResponse = z.object({
  ok: z.literal(true),
  data: z.enum(["ok"]),
  message: z.enum(["Success"]),
  requestId: z.string(),
});
