// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * A successful response object
 */
export const zOkResponse = z.object({
  ok: z.boolean(),
  data: z.unknown(),
  message: z.string(),
  requestId: z.string(),
});

export const zSession = z.object({
  id: z.string(),
  user: z.object({
    id: z.string(),
    name: z.string(),
    email: z
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
    phone: z.string(),
    role: z.string(),
    status: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
  createdAt: z.string(),
  expiresAt: z.string(),
});

export const zUser = z.object({
  id: z.string(),
  name: z.string(),
  email: z
    .email()
    .regex(
      /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
    ),
  phone: z.string(),
  role: z.string(),
  status: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const zApplicationId = z.enum([
  "salesforce",
  "hubspot",
  "stripe",
  "slack",
  "zendesk",
  "intercom",
]);

export const zChangeType = z.enum(["ADD", "UPDATE", "DELETE"]);

export const zConnectionStatus = z.enum(["connected", "disconnected", "pending", "error"]);

export const zIntegration = z.object({
  id: z.enum(["salesforce", "hubspot", "stripe", "slack", "zendesk", "intercom"]),
  name: z.string(),
  emoji: z.string(),
  status: z.enum(["synced", "syncing", "conflict", "error"]),
  lastSyncedAt: z.string(),
  version: z.string(),
});

export const zSyncApproval = z.object({
  application_name: z.string(),
  changes: z.array(
    z.object({
      id: z.string(),
      field_name: z.string(),
      change_type: z.enum(["ADD", "UPDATE", "DELETE"]),
      current_value: z.string().optional(),
      new_value: z.string().optional(),
    }),
  ),
});

export const zSyncChange = z.object({
  id: z.string(),
  field_name: z.string(),
  change_type: z.enum(["ADD", "UPDATE", "DELETE"]),
  current_value: z.string().optional(),
  new_value: z.string().optional(),
});

export const zSyncData = z.object({
  sync_approval: z.object({
    application_name: z.string(),
    changes: z.array(
      z.object({
        id: z.string(),
        field_name: z.string(),
        change_type: z.enum(["ADD", "UPDATE", "DELETE"]),
        current_value: z.string().optional(),
        new_value: z.string().optional(),
      }),
    ),
  }),
  metadata: z.record(z.string(), z.unknown()),
});

export const zSyncEvent = z.object({
  id: z.string(),
  field_name: z.string(),
  change_type: z.enum(["ADD", "UPDATE", "DELETE"]),
  current_value: z.string().optional(),
  new_value: z.string().optional(),
  syncId: z.string(),
  applicationId: z.enum(["salesforce", "hubspot", "stripe", "slack", "zendesk", "intercom"]),
  timestamp: z.string(),
  status: z.enum(["pending", "approved", "rejected", "failed"]),
  version: z.string(),
  resolvedBy: z.string(),
});

export const zSyncEventStatus = z.enum(["pending", "approved", "rejected", "failed"]);

export const zSyncStatus = z.enum(["synced", "syncing", "conflict", "error"]);

/**
 * An error response object
 */
export const zErrorResponse = z.object({
  ok: z.boolean(),
  errorCode: z.enum([
    "MALFORMED_INPUT",
    "NOT_FOUND",
    "UNAUTHORIZED",
    "SESSION_EXPIRED",
    "FORBIDDEN",
    "INTERNAL_SERVER_ERROR",
    "UNSPECIFIED_ERROR",
  ]),
  message: z.string(),
  requestId: z.string(),
});

export const zPostApiV1AuthLoginBody = z.object({
  email: z.email(),
  password: z.string(),
});

/**
 * A successful response object
 */
export const zPostApiV1AuthLoginResponse = z.object({
  ok: z.literal(true),
  data: z.object({
    session: z.object({
      id: z.string(),
      user: z.object({
        id: z.string(),
        name: z.string(),
        email: z.email(),
        phone: z.string(),
        role: z.string(),
        status: z.string(),
        createdAt: z.string(),
        updatedAt: z.string(),
      }),
      createdAt: z.string(),
      expiresAt: z.string(),
    }),
    token: z.string(),
  }),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

/**
 * A successful response object
 */
export const zGetApiV1AuthMeResponse = z.object({
  ok: z.literal(true),
  data: z.object({
    id: z.string(),
    name: z.string(),
    email: z.email(),
    phone: z.string(),
    role: z.string(),
    status: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

/**
 * A successful response object
 */
export const zGetApiV1MiscDebugResponse = z.object({
  ok: z.literal(true),
  data: z.unknown().optional(),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

export const zGetApiV1DataListQuery = z.object({
  search: z.string().optional(),
});

/**
 * A successful response object
 */
export const zGetApiV1DataListResponse = z.object({
  ok: z.literal(true),
  data: z.array(
    z.object({
      id: z.enum(["salesforce", "hubspot", "stripe", "slack", "zendesk", "intercom"]),
      name: z.string(),
      emoji: z.string(),
      status: z.enum(["synced", "syncing", "conflict", "error"]),
      lastSyncedAt: z.string(),
      version: z.string(),
    }),
  ),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

export const zGetApiV1DataSyncQuery = z.object({
  application_id: z.enum(["salesforce", "hubspot", "stripe", "slack", "zendesk", "intercom"]),
});

/**
 * Returns sync approval data from external API
 */
export const zGetApiV1DataSyncResponse = z.object({
  code: z.string(),
  message: z.string(),
  data: z.object({
    sync_approval: z.object({
      application_name: z.string(),
      changes: z.array(
        z.object({
          id: z.string(),
          field_name: z.string(),
          change_type: z.enum(["ADD", "UPDATE", "DELETE"]),
          current_value: z.string().optional(),
          new_value: z.string().optional(),
        }),
      ),
    }),
    metadata: z.record(z.string(), z.unknown()),
  }),
});

export const zGetApiV1DataByApplicationIdPath = z.object({
  application_id: z.string(),
});

/**
 * A successful response object
 */
export const zGetApiV1DataByApplicationIdResponse = z.object({
  ok: z.literal(true),
  data: z.object({
    id: z.enum(["salesforce", "hubspot", "stripe", "slack", "zendesk", "intercom"]),
    name: z.string(),
    emoji: z.string(),
    status: z.enum(["synced", "syncing", "conflict", "error"]),
    lastSyncedAt: z.string(),
    version: z.string(),
  }),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

export const zGetApiV1DataByApplicationIdHistoryPath = z.object({
  application_id: z.string(),
});

/**
 * A successful response object
 */
export const zGetApiV1DataByApplicationIdHistoryResponse = z.object({
  ok: z.literal(true),
  data: z.array(
    z.object({
      id: z.string(),
      field_name: z.string(),
      change_type: z.enum(["ADD", "UPDATE", "DELETE"]),
      current_value: z.string().optional(),
      new_value: z.string().optional(),
      syncId: z.string(),
      applicationId: z.enum(["salesforce", "hubspot", "stripe", "slack", "zendesk", "intercom"]),
      timestamp: z.string(),
      status: z.enum(["pending", "approved", "rejected", "failed"]),
      version: z.string(),
      resolvedBy: z.string(),
    }),
  ),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

export const zPostApiV1DataByApplicationIdResolveBody = z.object({
  syncChange: z.object({
    id: z.string(),
    field_name: z.string(),
    change_type: z.enum(["ADD", "UPDATE", "DELETE"]),
    current_value: z.string().optional(),
    new_value: z.string().optional(),
  }),
  action: z.enum(["approve", "reject"]),
});

export const zPostApiV1DataByApplicationIdResolvePath = z.object({
  application_id: z.enum(["salesforce", "hubspot", "stripe", "slack", "zendesk", "intercom"]),
});

/**
 * A successful response object
 */
export const zPostApiV1DataByApplicationIdResolveResponse = z.object({
  ok: z.literal(true),
  data: z.object({
    id: z.string(),
    field_name: z.string(),
    change_type: z.enum(["ADD", "UPDATE", "DELETE"]),
    current_value: z.string().optional(),
    new_value: z.string().optional(),
    syncId: z.string(),
    applicationId: z.enum(["salesforce", "hubspot", "stripe", "slack", "zendesk", "intercom"]),
    timestamp: z.string(),
    status: z.enum(["pending", "approved", "rejected", "failed"]),
    version: z.string(),
    resolvedBy: z.string(),
  }),
  message: z.enum(["Success"]),
  requestId: z.string(),
});
