// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * A successful response object
 */
export const zOkResponse = z.object({
  ok: z.boolean(),
  data: z.unknown(),
  message: z.string(),
  requestId: z.string(),
});

/**
 * An error response object
 */
export const zErrorResponse = z.object({
  ok: z.boolean(),
  errorCode: z.enum([
    "MALFORMED_INPUT",
    "NOT_FOUND",
    "UNAUTHORIZED",
    "FORBIDDEN",
    "INTERNAL_SERVER_ERROR",
    "UNSPECIFIED_ERROR",
  ]),
  message: z.string(),
  requestId: z.string(),
});

export const zGetApiV1MiscStatusData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * A successful response object
 */
export const zGetApiV1MiscStatusResponse = z.object({
  ok: z.literal(true),
  data: z.enum(["ok"]),
  message: z.enum(["Success"]),
  requestId: z.string(),
});

export const zGetApiV1MiscStatusWithParamsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    required: z.string().min(1),
    optional: z.optional(z.string().min(1)),
  }),
});

/**
 * A successful response object
 */
export const zGetApiV1MiscStatusWithParamsResponse = z.object({
  ok: z.literal(true),
  data: z.enum(["ok"]),
  message: z.enum(["Success"]),
  requestId: z.string(),
});
