// This file is auto-generated by @hey-api/openapi-ts

import type { AxiosError } from "axios";

import { type DefaultError, queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import type {
  GetApiV1AuthMeData,
  GetApiV1AuthMeError,
  GetApiV1AuthMeResponse,
  GetApiV1DataByApplicationIdData,
  GetApiV1DataByApplicationIdError,
  GetApiV1DataByApplicationIdHistoryData,
  GetApiV1DataByApplicationIdHistoryResponse,
  GetApiV1DataByApplicationIdResponse,
  GetApiV1DataListData,
  GetApiV1DataListResponse,
  GetApiV1DataSyncData,
  GetApiV1DataSyncError,
  GetApiV1DataSyncResponse,
  GetApiV1MiscDebugData,
  GetApiV1MiscDebugResponse,
  PostApiV1AuthLoginData,
  PostApiV1AuthLoginError,
  PostApiV1AuthLoginResponse,
  PostApiV1DataByApplicationIdResolveData,
  PostApiV1DataByApplicationIdResolveResponse,
} from "../types.gen";

import { client } from "../client.gen";
import { AuthService, IntegrationsService, MiscService, type Options } from "../sdk.gen";

/**
 * Login with email and password
 *
 * Authenticate user and set httpOnly session cookie
 */
export const postApiV1AuthLoginMutation = (
  options?: Partial<Options<PostApiV1AuthLoginData>>,
): UseMutationOptions<
  PostApiV1AuthLoginResponse,
  AxiosError<PostApiV1AuthLoginError>,
  Options<PostApiV1AuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthLoginResponse,
    AxiosError<PostApiV1AuthLoginError>,
    Options<PostApiV1AuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await AuthService.postApiV1AuthLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiV1AuthMeQueryKey = (options?: Options<GetApiV1AuthMeData>) =>
  createQueryKey("getApiV1AuthMe", options, false, ["Auth"]);

/**
 * Get current user session
 *
 * Returns the current user's session information
 */
export const getApiV1AuthMeOptions = (options?: Options<GetApiV1AuthMeData>) =>
  queryOptions<
    GetApiV1AuthMeResponse,
    AxiosError<GetApiV1AuthMeError>,
    GetApiV1AuthMeResponse,
    ReturnType<typeof getApiV1AuthMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await AuthService.getApiV1AuthMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthMeQueryKey(options),
  });

export const getApiV1MiscDebugQueryKey = (options?: Options<GetApiV1MiscDebugData>) =>
  createQueryKey("getApiV1MiscDebug", options, false, ["Misc"]);

/**
 * Get Debug
 *
 * Get debug info
 */
export const getApiV1MiscDebugOptions = (options?: Options<GetApiV1MiscDebugData>) =>
  queryOptions<
    GetApiV1MiscDebugResponse,
    AxiosError<DefaultError>,
    GetApiV1MiscDebugResponse,
    ReturnType<typeof getApiV1MiscDebugQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MiscService.getApiV1MiscDebug({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1MiscDebugQueryKey(options),
  });

export const getApiV1DataListQueryKey = (options?: Options<GetApiV1DataListData>) =>
  createQueryKey("getApiV1DataList", options, false, ["Integrations"]);

/**
 * Get Integrations List
 *
 * Get list of all integrations with their sync status
 */
export const getApiV1DataListOptions = (options?: Options<GetApiV1DataListData>) =>
  queryOptions<
    GetApiV1DataListResponse,
    AxiosError<DefaultError>,
    GetApiV1DataListResponse,
    ReturnType<typeof getApiV1DataListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await IntegrationsService.getApiV1DataList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1DataListQueryKey(options),
  });

export const getApiV1DataSyncQueryKey = (options: Options<GetApiV1DataSyncData>) =>
  createQueryKey("getApiV1DataSync", options, false, ["Integrations"]);

/**
 * [EXTERNAL] Get Data Sync
 *
 * Proxy to external API to get sync approval data for an application
 */
export const getApiV1DataSyncOptions = (options: Options<GetApiV1DataSyncData>) =>
  queryOptions<
    GetApiV1DataSyncResponse,
    AxiosError<GetApiV1DataSyncError>,
    GetApiV1DataSyncResponse,
    ReturnType<typeof getApiV1DataSyncQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await IntegrationsService.getApiV1DataSync({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1DataSyncQueryKey(options),
  });

export const getApiV1DataByApplicationIdQueryKey = (
  options: Options<GetApiV1DataByApplicationIdData>,
) => createQueryKey("getApiV1DataByApplicationId", options, false, ["Integrations"]);

/**
 * Get Integration Details
 *
 * Get detailed information about a specific integration
 */
export const getApiV1DataByApplicationIdOptions = (
  options: Options<GetApiV1DataByApplicationIdData>,
) =>
  queryOptions<
    GetApiV1DataByApplicationIdResponse,
    AxiosError<GetApiV1DataByApplicationIdError>,
    GetApiV1DataByApplicationIdResponse,
    ReturnType<typeof getApiV1DataByApplicationIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await IntegrationsService.getApiV1DataByApplicationId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1DataByApplicationIdQueryKey(options),
  });

export const getApiV1DataByApplicationIdHistoryQueryKey = (
  options: Options<GetApiV1DataByApplicationIdHistoryData>,
) => createQueryKey("getApiV1DataByApplicationIdHistory", options, false, ["Integrations"]);

/**
 * Get Sync History
 *
 * Get historical sync events for an integration
 */
export const getApiV1DataByApplicationIdHistoryOptions = (
  options: Options<GetApiV1DataByApplicationIdHistoryData>,
) =>
  queryOptions<
    GetApiV1DataByApplicationIdHistoryResponse,
    AxiosError<DefaultError>,
    GetApiV1DataByApplicationIdHistoryResponse,
    ReturnType<typeof getApiV1DataByApplicationIdHistoryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await IntegrationsService.getApiV1DataByApplicationIdHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1DataByApplicationIdHistoryQueryKey(options),
  });

/**
 * Resolve Sync Changes
 *
 * Approve or reject sync changes
 */
export const postApiV1DataByApplicationIdResolveMutation = (
  options?: Partial<Options<PostApiV1DataByApplicationIdResolveData>>,
): UseMutationOptions<
  PostApiV1DataByApplicationIdResolveResponse,
  AxiosError<DefaultError>,
  Options<PostApiV1DataByApplicationIdResolveData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1DataByApplicationIdResolveResponse,
    AxiosError<DefaultError>,
    Options<PostApiV1DataByApplicationIdResolveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await IntegrationsService.postApiV1DataByApplicationIdResolve({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
