// This file is auto-generated by @hey-api/openapi-ts

import type { AxiosError } from "axios";

import { type DefaultError, queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import type {
  GetApiV1ApplicationsListData,
  GetApiV1ApplicationsListResponse,
  GetApiV1AuthMeData,
  GetApiV1AuthMeError,
  GetApiV1AuthMeResponse,
  GetApiV1DataSyncData,
  GetApiV1DataSyncError,
  GetApiV1DataSyncResponse,
  GetApiV1MiscStatusData,
  GetApiV1MiscStatusResponse,
  GetApiV1MiscStatusWithParamsData,
  GetApiV1MiscStatusWithParamsError,
  GetApiV1MiscStatusWithParamsResponse,
  PostApiV1AuthLoginData,
  PostApiV1AuthLoginError,
  PostApiV1AuthLoginResponse,
} from "../types.gen";

import { client } from "../client.gen";
import {
  ApplicationsService,
  AuthService,
  DataService,
  MiscService,
  type Options,
} from "../sdk.gen";

/**
 * Login with email and password
 *
 * Authenticate user and set httpOnly session cookie
 */
export const postApiV1AuthLoginMutation = (
  options?: Partial<Options<PostApiV1AuthLoginData>>,
): UseMutationOptions<
  PostApiV1AuthLoginResponse,
  AxiosError<PostApiV1AuthLoginError>,
  Options<PostApiV1AuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthLoginResponse,
    AxiosError<PostApiV1AuthLoginError>,
    Options<PostApiV1AuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await AuthService.postApiV1AuthLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiV1AuthMeQueryKey = (options?: Options<GetApiV1AuthMeData>) =>
  createQueryKey("getApiV1AuthMe", options, false, ["Auth"]);

/**
 * Get current user session
 *
 * Returns the current user's session information
 */
export const getApiV1AuthMeOptions = (options?: Options<GetApiV1AuthMeData>) =>
  queryOptions<
    GetApiV1AuthMeResponse,
    AxiosError<GetApiV1AuthMeError>,
    GetApiV1AuthMeResponse,
    ReturnType<typeof getApiV1AuthMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await AuthService.getApiV1AuthMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthMeQueryKey(options),
  });

export const getApiV1MiscStatusQueryKey = (options?: Options<GetApiV1MiscStatusData>) =>
  createQueryKey("getApiV1MiscStatus", options, false, ["Misc"]);

/**
 * Get Status
 *
 * Get ok status
 */
export const getApiV1MiscStatusOptions = (options?: Options<GetApiV1MiscStatusData>) =>
  queryOptions<
    GetApiV1MiscStatusResponse,
    AxiosError<DefaultError>,
    GetApiV1MiscStatusResponse,
    ReturnType<typeof getApiV1MiscStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MiscService.getApiV1MiscStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1MiscStatusQueryKey(options),
  });

export const getApiV1MiscStatusWithParamsQueryKey = (
  options: Options<GetApiV1MiscStatusWithParamsData>,
) => createQueryKey("getApiV1MiscStatusWithParams", options, false, ["Misc"]);

/**
 * Get Status with Params
 *
 * Get ok status
 */
export const getApiV1MiscStatusWithParamsOptions = (
  options: Options<GetApiV1MiscStatusWithParamsData>,
) =>
  queryOptions<
    GetApiV1MiscStatusWithParamsResponse,
    AxiosError<GetApiV1MiscStatusWithParamsError>,
    GetApiV1MiscStatusWithParamsResponse,
    ReturnType<typeof getApiV1MiscStatusWithParamsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await MiscService.getApiV1MiscStatusWithParams({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1MiscStatusWithParamsQueryKey(options),
  });

export const getApiV1ApplicationsListQueryKey = (options?: Options<GetApiV1ApplicationsListData>) =>
  createQueryKey("getApiV1ApplicationsList", options, false, ["Applications"]);

/**
 * Get Applications List
 *
 * Get list of all applications with their sync status
 */
export const getApiV1ApplicationsListOptions = (options?: Options<GetApiV1ApplicationsListData>) =>
  queryOptions<
    GetApiV1ApplicationsListResponse,
    AxiosError<DefaultError>,
    GetApiV1ApplicationsListResponse,
    ReturnType<typeof getApiV1ApplicationsListQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await ApplicationsService.getApiV1ApplicationsList({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1ApplicationsListQueryKey(options),
  });

export const getApiV1DataSyncQueryKey = (options: Options<GetApiV1DataSyncData>) =>
  createQueryKey("getApiV1DataSync", options, false, ["Data"]);

/**
 * [EXTERNAL] Get Data Sync
 *
 * Proxy to external API to get sync approval data for an application
 */
export const getApiV1DataSyncOptions = (options: Options<GetApiV1DataSyncData>) =>
  queryOptions<
    GetApiV1DataSyncResponse,
    AxiosError<GetApiV1DataSyncError>,
    GetApiV1DataSyncResponse,
    ReturnType<typeof getApiV1DataSyncQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await DataService.getApiV1DataSync({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1DataSyncQueryKey(options),
  });
